name: Go Test

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Set up Go
        uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...
